{% set name = "hub_v1" %}
{% set version = "1.3.7" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - hub_v1 = hub_v1.cli.command:cli
    - hub_v1-local = hub_v1.cli.local:cli
    - hub_v1-dev = hub_v1.cli.dev:cli
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - azure-storage-blob
    - boto3
    - cachey
    - click
    - cloudpickle
    - fsspec
    - gcsfs
    - lz4
    - msgpack-python
    - numpy
    - outdated
    - pathos
    - pillow
    - pip
    - psutil
    - python
    - requests
    - s3fs
    - tqdm
    - zarr
  run:
    - azure-storage-blob
    - boto3
    - cachey
    - click
    - cloudpickle
    - fsspec
    - gcsfs
    - lz4
    - msgpack-python
    - numpy
    - outdated
    - pathos
    - pillow
    - psutil
    - python
    - requests
    - s3fs
    - tqdm
    - zarr

test:
  imports:
    - hub_v1
    - hub_v1.api
    - hub_v1.cli
    - hub_v1.client
    - hub_v1.codec
    - hub_v1.collections
    - hub_v1.collections.dataset
    - hub_v1.collections.tensor
    - hub_v1.compute
    - hub_v1.schema
    - hub_v1.store
    - hub_v1.store.tests
  commands:
    - hub_v1 --help
    - hub_v1-local --help
    - hub_v1-dev --help
  requires:
    - mock >=1.0.1
    - pytest

about:
  home: "https://github.com/activeloopai/Hub"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file: 
  summary: "Activeloop Hub"
  doc_url: "https://docs.activeloop.ai/en/latest/"
  dev_url: 

extra:
  recipe-maintainers:
    - haiyangdeperci
