# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches:
      - "feature/github-actions"

jobs:
  build:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }} - ${{ github.event_name }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        python-version:
          - 3.8
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
